apiVersion: v1
kind: Secret
metadata:
  name: k8s-port-audit-ziti-admin
  namespace: port-audit
type: Opaque
stringData:
  ZITI_DEFAULT_CONTROLLER_URL: https://192.168.198.128:31280
  ZITI_DEFAULT_USERNAME: admin
  ZITI_DEFAULT_PASSWORD: change-me
