apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ziti-controller-db
  namespace: openziti
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
